### ISSUE TITLE
return []bytes from XML() instead of strings?

### ISSUE THREAD

**Issue by figlief** [agrison/go-tablib#2]
I wish the XML(), JSON(), etc formatters returned []byte slices instead of strings.

I need to convert the string to []byte for nearly everything I want to do: even for a simple ioutil.WriteFile.

You covert to string then i have to convert back to []byte !  Two costly operations, both in terms of time and memory usage, to do nothing.
If I need bytes I can easily use bytes() myself.

Very good package though. Love it despite the niggles.

**Comment by agrison** [comment]
I understand what you're saying, it is indeed a pain to have convert between `string` and `[]byte` so often. I'll think about it tomorrow while on the train :)

**Comment by agrison** [comment]
This is what I implemented this morning:
Any of the `JSON`, `CSV`, `XML` and other export formats are now returning a `(*Exportable, error)` instead of `(string, error)`. Only the `Tabular` and `Markdown` does return an `*Exportable` and no error because the `gotabular` library does not return any error.

This `Exportable` struct has four methods which are:
- `String()` to get the exported content as a `string``
- `Bytes()` to get the exported content as a `[]byte`
- `WriteTo(io.Writer)` to write the exported content to an `io.Writer`
- `WriteFile(string, os.FileMode)` which delegates to `ioutil.WriteFile(string, []byte, os.FileMode)`

The `Exportable` struct does hold an underlying `bytes.Buffer` which has been filled by the library during the execution of the various export methods. This way you have a `[]byte` directly by calling `Bytes()` (`bytes.Buffer` is just slicing the underlying byte array to the current buffer length), and handy methods to write the content to a io.writer or a file. 
The `String()` method will be called automatically when trying to print the exported Dataset/Databook which is OK for debugging, and can be called directly if the caller really wants a `string`.

**Comment by figlief** [comment]
excellent thank you! and an incredibly fast response!
