### ISSUE TITLE
problem docs and AppendValuesTagged

### ISSUE THREAD

**Issue by figlief** [agrison/go-tablib#3]
AppendValuesTagged has the same signature as AppendValues, no way of  specifying tags.

In the docs this appears

ds.AppendTagged("Bentley", "Continental")

which is wrong.

In addition all use of CSV() etc in the docs need  to allow for two return values as it now returns an error value.

**Comment by agrison** [comment]
You're right `AppendValuesTagged` tags nothing, I forgot to implement it since it takes a `interface{}...` and should also take a `string...` for tags. 

I'm wondering if that method should be deleted since it's already possible to do the same thing with `AppendTagged`. Or implement it using only `interface{}...` checking for boundaries adding the N first as column values and casting the rest as string to use them as tags.

In the README it should have been `ds.AppendValues("Bentley", "Continental")` and not `ds.AppendTagged("Bentley", "Continental")`. Bad copy/paste :)

**Comment by agrison** [comment]
The `AppendValuesTagged` has been implemented, and the README has been corrected. 
Thanks for noticing :smile:
